In [374]:
# 變數設定

import pandas
import numpy as np

csv_files = [
            r'test/record_2023_03_06_15_56_39_363.csv'
            ]

csv_datas  = []
mode_datas = []
# 讀取所有csv檔案
for file in csv_files:
    print(file)
    csv_datas.append(pandas.read_csv(file))

# 新增一個字典將 MODE 分開
for df in csv_datas:
    mode_dict = {}
    for mode in df['Mode']:
        mode_df = df[df['Mode'] == mode].copy()
        mode_df = mode_df.drop('Mode', axis = 1)
        mode_dict[mode] = mode_df
    mode_datas.append(mode_dict)


測試/record_2023_03_06_15_56_39_363.csv


In [375]:
# 顯示 第一組 Normal Data 轉成只有Label
for m_dict in mode_datas:
    m_dict["NORMAL"] = m_dict["NORMAL"].filter(regex='^L')
    m_dict["FREE"] = m_dict["FREE"].filter(regex='^L')

# 查看第一組 Normal Data 轉成只有 Label 的資料
mode_datas[0]["NORMAL"]

L11     L12     L13     L21      L22      L23      L31     L32  \
0      Carpet       Q  Carpet  Carpet  Scatter        J      Boy  Carpet   
1           K     Boy       Q       K  Scatter        J        K    Girl   
2        Girl       A       K  Carpet  Scatter        J  Scatter       A   
3           K     Boy       A       J        Q     Wild  Scatter       A   
4           K     Boy       Q       K        A        K     Girl  Carpet   
...       ...     ...     ...     ...      ...      ...      ...     ...   
2125   Carpet       Q  Carpet     Boy        K     WILD        J       A   
2126        J    Girl       A       J   Carpet  Scatter        A       Q   
2127        K       K       J     Boy        K        A        J       A   
2128        A       J    Girl       Q  Scatter        J  Scatter       J   
2129  Scatter  Carpet       A       K        Q        Q   Carpet       Q   

         L33     L41     L42     L43     L51  L52     L53  
0          Q  Carpet       A       Q       A    J       Q  
1          A       J       J     Boy       A    J       J  
2        Boy  Carpet       A       Q       A    J       Q  
3        Boy       K       Q       A       A    A     Boy  
4          K       J  Carpet       J       A    J       Q  
...      ...     ...     ...     ...     ...  ...     ...  
2125  Carpet       A       J  Carpet       K  Boy       A  
2126  Carpet       A    Girl     Boy     Boy    J  Carpet  
2127       K     Boy       Q    Girl     Boy    K       A  
2128  Carpet       J     Boy       K  Carpet    K    Girl  
2129    Girl    Girl       K    Girl       A    J       J  

[1912 rows x 15 columns]

In [376]:
# 定義一個轉換字典將所有資料轉成編號，用於之後方便計算
label_map = {"A":0, "J":1, "Q":2, "K":3, "Boy":4, "Girl":5, "WILD":6, "Wild":6, "Scatter":7, "Carpet":8}
label_list = ["A","J", "Q", "K", "Boy", "Girl" , "Wild", "Scatter", "Carpet"]

for mode_data in mode_datas:
    mode_data["NORMAL"] = mode_data["NORMAL"].applymap(lambda x: label_map.get(x, x))
    mode_data["FREE"] = mode_data["FREE"].applymap(lambda x: label_map.get(x, x))

# 顯示第一組 的 轉換 資料 (NORMAL)
mode_datas[0]["NORMAL"]

L11  L12  L13  L21  L22  L23  L31  L32  L33  L41  L42  L43  L51  L52  \
0       8    2    8    8    7    1    4    8    2    8    0    2    0    1   
1       3    4    2    3    7    1    3    5    0    1    1    4    0    1   
2       5    0    3    8    7    1    7    0    4    8    0    2    0    1   
3       3    4    0    1    2    6    7    0    4    3    2    0    0    0   
4       3    4    2    3    0    3    5    8    3    1    8    1    0    1   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
2125    8    2    8    4    3    6    1    0    8    0    1    8    3    4   
2126    1    5    0    1    8    7    0    2    8    0    5    4    4    1   
2127    3    3    1    4    3    0    1    0    3    4    2    5    4    3   
2128    0    1    5    2    7    1    7    1    8    1    4    3    8    3   
2129    7    8    0    3    2    2    8    2    5    5    3    5    0    1   

      L53  
0       2  
1       1  
2       2  
3       4  
4       2  
...   ...  
2125    0  
2126    8  
2127    0  
2128    5  
2129    1  

[1912 rows x 15 columns]

In [377]:
# 轉成矩陣

for mode_data in mode_datas:
    mode_data["NORMAL"] = mode_data["NORMAL"].to_numpy().reshape(-1, 5, 3)
    mode_data["FREE"] = mode_data["FREE"].to_numpy().reshape(-1, 5, 3)



In [378]:
# 目前 DATA = [{"NORMAL":array shape (475, 5, 3), "NORMAL":array shape (475, 5, 3)} , {data2}, {data3}, {data4}]
mode_datas[0]["NORMAL"]

array([[[8, 2, 8],
        [8, 7, 1],
        [4, 8, 2],
        [8, 0, 2],
        [0, 1, 2]],

       [[3, 4, 2],
        [3, 7, 1],
        [3, 5, 0],
        [1, 1, 4],
        [0, 1, 1]],

       [[5, 0, 3],
        [8, 7, 1],
        [7, 0, 4],
        [8, 0, 2],
        [0, 1, 2]],

       ...,

       [[3, 3, 1],
        [4, 3, 0],
        [1, 0, 3],
        [4, 2, 5],
        [4, 3, 0]],

       [[0, 1, 5],
        [2, 7, 1],
        [7, 1, 8],
        [1, 4, 3],
        [8, 3, 5]],

       [[7, 8, 0],
        [3, 2, 2],
        [8, 2, 5],
        [5, 3, 5],
        [0, 1, 1]]])

In [379]:
# 查看 L1輪帶表的資料，475把中所記錄的L1輪帶資料
for arr in mode_datas[0]["NORMAL"][:, 0]:
    print(arr)

[8 2 8]
[3 4 2]
[5 0 3]
[3 4 0]
[3 4 2]
[5 2 2]
[2 5 0]
[3 4 7]
[0 5 2]
[3 5 2]
[0 7 1]
[8 0 2]
[2 1 5]
[2 1 5]
[2 2 5]
[2 4 1]
[1 5 1]
[0 7 8]
[5 2 2]
[2 2 4]
[4 1 8]
[0 8 4]
[2 2 4]
[1 8 2]
[0 2 5]
[8 3 4]
[2 2 5]
[8 0 7]
[7 8 0]
[1 8 0]
[1 2 3]
[5 2 3]
[2 3 1]
[3 1 7]
[3 4 7]
[0 3 5]
[1 7 3]
[4 7 8]
[3 4 2]
[1 5 1]
[5 1 8]
[1 7 3]
[1 8 2]
[0 5 2]
[4 3 3]
[0 5 2]
[1 0 5]
[3 3 1]
[3 3 1]
[3 3 1]
[3 3 1]
[1 8 3]
[2 5 2]
[5 2 2]
[1 0 5]
[2 5 2]
[1 1 2]
[1 5 1]
[5 1 8]
[7 8 2]
[5 0 3]
[7 3 4]
[1 5 0]
[3 3 1]
[5 2 3]
[8 0 2]
[4 0 1]
[1 8 0]
[8 0 8]
[5 0 7]
[5 2 2]
[4 0 1]
[0 3 4]
[5 0 3]
[1 8 0]
[1 8 0]
[8 0 2]
[2 2 4]
[3 5 2]
[5 0 7]
[5 2 2]
[5 2 3]
[5 0 7]
[1 5 0]
[8 0 8]
[5 0 7]
[1 2 3]
[3 4 2]
[3 5 2]
[3 4 0]
[1 7 3]
[3 4 2]
[4 2 1]
[0 3 4]
[1 2 3]
[0 2 5]
[4 3 3]
[5 0 3]
[2 3 4]
[0 3 5]
[0 5 2]
[8 2 8]
[2 3 4]
[1 8 3]
[2 5 0]
[8 0 3]
[2 3 1]
[2 5 2]
[1 1 2]
[5 0 3]
[8 0 2]
[4 1 8]
[0 1 5]
[2 5 0]
[8 4 1]
[8 2 1]
[1 8 0]
[0 7 1]
[3 1 0]
[0 7 1]
[1 8 2]
[8 2 8]
[4 1 8]
[8 2 1]
[2 1 1]


In [380]:
def count_labels(L, name):
    label_arr, counts = np.unique(L, axis=0, return_counts=True)

    # Find the indices of label categories with more than one item
    indices = np.where(counts > 1)[0]
    
    # Sort the label categories by count (from high to low) and keep only those with more than one item
    sorted_indices = np.argsort(-counts[indices])
    sorted_counts = counts[indices][sorted_indices]
    sorted_labels = [label_arr[i] for i in indices[sorted_indices]]
    
    num = 0
    for label, count in zip(sorted_labels, sorted_counts):
        print(f"{label} appears {count} items.\t{count/sum(counts)*100:.2f}% ({count}/{sum(sorted_counts)})")
        num += 1
        
    print(f"L{name}: {num} categories with more than one item.")
    print()
    
    return sorted_counts/sum(sorted_counts)*100


count_labels(mode_datas[0]["NORMAL"][:, 0], 1)
#將資料存為百分比

mode_percentages = []

for data in mode_datas:
    mode_percentages.append([{"NORMAL":count_labels(data["NORMAL"][:, L], L+1), "FREE":count_labels(data["FREE"][:, L], L+1)} for L in range(5)])
    

[5 2 2] appears 64 items.	3.35% (64/1909)
[1 8 0] appears 63 items.	3.29% (63/1909)
[4 1 8] appears 52 items.	2.72% (52/1909)
[5 2 3] appears 47 items.	2.46% (47/1909)
[7 8 2] appears 43 items.	2.25% (43/1909)
[4 0 1] appears 42 items.	2.20% (42/1909)
[1 1 2] appears 42 items.	2.20% (42/1909)
[3 1 0] appears 41 items.	2.14% (41/1909)
[4 3 3] appears 40 items.	2.09% (40/1909)
[7 8 0] appears 38 items.	1.99% (38/1909)
[2 8 0] appears 37 items.	1.94% (37/1909)
[8 2 1] appears 36 items.	1.88% (36/1909)
[3 4 7] appears 36 items.	1.88% (36/1909)
[2 3 1] appears 36 items.	1.88% (36/1909)
[8 0 7] appears 36 items.	1.88% (36/1909)
[2 2 4] appears 36 items.	1.88% (36/1909)
[0 8 4] appears 35 items.	1.83% (35/1909)
[8 3 4] appears 35 items.	1.83% (35/1909)
[2 5 0] appears 35 items.	1.83% (35/1909)
[7 1 8] appears 35 items.	1.83% (35/1909)
[2 5 2] appears 34 items.	1.78% (34/1909)
[2 1 5] appears 34 items.	1.78% (34/1909)
[1 7 3] appears 34 items.	1.78% (34/1909)
[8 0 2] appears 34 items.	1.78% (3

In [381]:
# 設定基準值 MG FG
MG_Percent = [60, 61, 61, 53, 53]
FG_Percent = [50, 50, 50, 62, 50]

In [382]:
mode_percentages[0][0]["NORMAL"]

array([3.3525406 , 3.30015715, 2.72393924, 2.462022  , 2.25248821,
       2.20010477, 2.20010477, 2.14772132, 2.09533787, 1.99057098,
       1.93818753, 1.88580409, 1.88580409, 1.88580409, 1.88580409,
       1.88580409, 1.83342064, 1.83342064, 1.83342064, 1.83342064,
       1.78103719, 1.78103719, 1.78103719, 1.78103719, 1.78103719,
       1.78103719, 1.72865375, 1.72865375, 1.72865375, 1.72865375,
       1.72865375, 1.6762703 , 1.6762703 , 1.6762703 , 1.62388685,
       1.5715034 , 1.5715034 , 1.5715034 , 1.5715034 , 1.51911996,
       1.51911996, 1.51911996, 1.51911996, 1.46673651, 1.46673651,
       1.41435306, 1.41435306, 1.36196962, 1.36196962, 1.30958617,
       1.25720272, 1.25720272, 1.25720272, 1.25720272, 1.15243583,
       1.10005238, 1.04766894, 0.10476689])

In [383]:
# 計算均方差

def MSE(data, baseline):
    return np.square(data - baseline).mean(axis=0)

normal_mse_percentages = []
free_mse_percentages = []

for mode in mode_percentages:
    for index, mg in enumerate(MG_Percent):
        normal_mse_percentages.append( {"NORMAL" : MSE(mode[index]["NORMAL"], (1/float(mg))*100.0)} )

for mode in mode_percentages:
    for index, mg in enumerate(FG_Percent):
        free_mse_percentages.append( {"FREE": MSE(mode[index]["FREE"], (1/float(mg))*100.0)} )

normal_mse_percentages


[{'NORMAL': 0.24035689485363496},
 {'NORMAL': 0.1820940563649568},
 {'NORMAL': 0.13910863999432932},
 {'NORMAL': 0.1287761745510907},
 {'NORMAL': 0.31974974035034975}]

In [384]:
# 試串

label_arr, counts = np.unique(mode_datas[0]["NORMAL"][:, 0], axis=0, return_counts=True)
# Find the indices of label categories with more than one item
indices = np.where(counts/float(sum(counts)) *100.0 > 1 )[0]

# Sort the label categories by count (from high to low) and keep only those with more than one item
# sorted_indices = np.argsort(-counts[indices])
sorted_indices = np.argsort(indices)
sorted_counts = counts[indices][sorted_indices]
sorted_labels = [label_arr[i] for i in indices[sorted_indices]]

sorted_labels

[array([0, 1, 5]),
 array([0, 2, 5]),
 array([0, 3, 4]),
 array([0, 3, 5]),
 array([0, 5, 2]),
 array([0, 7, 1]),
 array([0, 7, 8]),
 array([0, 8, 4]),
 array([1, 0, 5]),
 array([1, 1, 2]),
 array([1, 2, 3]),
 array([1, 5, 0]),
 array([1, 5, 1]),
 array([1, 7, 3]),
 array([1, 8, 0]),
 array([1, 8, 2]),
 array([1, 8, 3]),
 array([2, 1, 1]),
 array([2, 1, 5]),
 array([2, 2, 4]),
 array([2, 2, 5]),
 array([2, 3, 1]),
 array([2, 3, 4]),
 array([2, 4, 1]),
 array([2, 5, 0]),
 array([2, 5, 2]),
 array([2, 8, 0]),
 array([3, 1, 0]),
 array([3, 1, 7]),
 array([3, 3, 1]),
 array([3, 4, 0]),
 array([3, 4, 2]),
 array([3, 4, 3]),
 array([3, 4, 7]),
 array([3, 5, 2]),
 array([4, 0, 1]),
 array([4, 1, 8]),
 array([4, 2, 1]),
 array([4, 3, 3]),
 array([4, 7, 8]),
 array([5, 0, 3]),
 array([5, 0, 7]),
 array([5, 1, 8]),
 array([5, 2, 2]),
 array([5, 2, 3]),
 array([7, 1, 8]),
 array([7, 3, 4]),
 array([7, 8, 0]),
 array([7, 8, 2]),
 array([8, 0, 2]),
 array([8, 0, 3]),
 array([8, 0, 7]),
 array([8, 0

In [385]:
# 檢查正確性 (總和要是 1，可以發現2000筆資料中 L1未曾出現 Label6 : Wild)
# np.sum(transform_arr, axis=1 , dtype=float)
# zip(sorted_labels, sorted_counts)

In [387]:
def transform_matrix(labels_list):
    transform_arr = np.zeros((len(label_list), len(label_list)), dtype=float)
    for data,count in labels_list:
        transform_arr[data[0]][data[1]] += float(count)
        transform_arr[data[1]][data[2]] += float(count)
    # Normalize the rows of the array
    row_sums = transform_arr.sum(axis=1)
    nonzero_row_indices = row_sums.nonzero()[0]
    transform_arr[nonzero_row_indices] /= row_sums[nonzero_row_indices][:, np.newaxis]
    return transform_arr

def generate_label(list_len, limit = False):
    data = zip(sorted_labels, sorted_counts)
    matrix = transform_matrix(data)
    # 選一個連續 label 並轉成列表
    random = np.random.choice(len(sorted_labels))
    gen_list = []
    for label in sorted_labels[random]:
        gen_list.append(label)
    check_list = [True for i in range(len(sorted_labels))] if limit else [False for i in range(len(sorted_labels))]
    check_list[random] = False


    # 當小於指定長度就一直生成
    while sum(check_list) or (len(gen_list) <=  list_len):

        # 抓取最後一個並且映射到轉置矩陣之中
        current_arr = matrix[gen_list[-1]]
        # 或取下一個要接的 LIST 的索引值
        next_index = np.random.choice(len(current_arr), p=current_arr)

        if limit :
            for idx, label in enumerate(sorted_labels):
                if np.array_equal(label, [gen_list[-2], gen_list[-1], int(next_index)]):
                    for label in sorted_labels:
                        if np.array_equal(label[:2], [gen_list[-1], int(next_index)]):
                            gen_list.append(int(next_index))
                            check_list[idx] = False
                            # if len(gen_list) >= list_len : 
                            #     return []
                            break
                    break
        else:
            gen_list.append(int(next_index))

    return gen_list

print(len(generate_label(0, True)))


371


In [388]:
def cucular_mse(lists):
    appear_rate = [0 for i in range(len(label_list))]

    for label, count in zip(sorted_labels,sorted_counts):
        for _ in range(count):
            for element in label:
                appear_rate[element] +=1
    appear_rate = np.array(appear_rate, dtype =float)
    appear_rate /= sum(appear_rate)

    avg_mse = 0

    for l in lists:
        rate = [0 for i in range(len(label_list))]
        for element in l:
            rate[element] += 1
        rate = np.array(rate, dtype =float)
        rate /= sum(rate)
        avg_mse += MSE(rate*100, appear_rate*100)
        
    return avg_mse / len(lists)


In [ ]:
# 收割一下
for gen_num in range(100,3001,100):
    gen_list = []
    for iter in range(100):
        gen_list.append(generate_label(gen_num))
    print(f'generate lable list {gen_num} MSE : {cucular_mse(gen_list):.2f} %')


In [ ]:
# 收割一下
for gen_num in range(100,3001,100):
    gen_list = []
    gen_len = 0
    for iter in range(100):
        gen_list.append(generate_label(gen_num, limit=True))
    for g_list in gen_list:
        gen_len += len(g_list)
    print(f'generate lable list {int(gen_len / len(gen_list))} MSE : {cucular_mse(gen_list):.2f} %')

In [405]:
# 收割一下
while True:
    if (mse := cucular_mse(gen := [generate_label(0, limit=True)])) and len(gen[0]) < 100:
        print(f'generate lable list {len(gen[0])} MSE : {mse:.2f} %')

generate lable list 98 MSE : 2.50 %
generate lable list 87 MSE : 0.76 %
generate lable list 95 MSE : 1.06 %
generate lable list 98 MSE : 2.63 %
generate lable list 96 MSE : 1.13 %
generate lable list 88 MSE : 4.06 %
generate lable list 98 MSE : 4.32 %
generate lable list 84 MSE : 4.93 %
generate lable list 82 MSE : 2.15 %
generate lable list 92 MSE : 2.43 %


KeyboardInterrupt: 