In [51]:
import numpy as np
import itertools

# Define the list of labels
labels = [['A', 'B', 'C'], ['D', 'A', 'B'], ['B', 'C', 'D']]

# Flatten the list of labels into a one-dimensional array
flat_labels = list(itertools.chain(*labels))
print(flat_labels)
# Define the transition matrix
matrix = np.array([[0.0, 0.5, 0.5, 0.0],
                   [0.5, 0.0, 0.5, 0.0],
                   [1/3, 1/3, 0.0, 1/3],
                   [0.5, 0.5, 0.0, 0.0]])

['A', 'B', 'C', 'D', 'A', 'B', 'B', 'C', 'D']


In [57]:
# Define the starting label
start_label = np.random.choice(flat_labels)
# Initialize the new list with the starting label
new_list = [start_label]

# Generate the new list
while len(new_list) < 200:
    # Get the last label in the new list
    last_label = new_list[-1]
    print(last_label)
    # Find the index of the last label in the list of flat labels
    current_index = flat_labels.index(last_label)
    print(current_index)
    
    
    # Use the transition matrix to randomly select the next label
    next_index = np.random.choice(len(matrix[current_index]), p=matrix[current_index])
    next_label = flat_labels[next_index]
    # Add the next label to the new list
    new_list.append(next_label)

print(new_list)

B
1
[0.5 0.  0.5 0. ]
0
A
0
[0.  0.5 0.5 0. ]
2
C
2
[0.33333333 0.33333333 0.         0.33333333]
0
A
0
[0.  0.5 0.5 0. ]
2
C
2
[0.33333333 0.33333333 0.         0.33333333]
1
B
1
[0.5 0.  0.5 0. ]
0
A
0
[0.  0.5 0.5 0. ]
1
B
1
[0.5 0.  0.5 0. ]
2
C
2
[0.33333333 0.33333333 0.         0.33333333]
0
A
0
[0.  0.5 0.5 0. ]
2
C
2
[0.33333333 0.33333333 0.         0.33333333]
0
A
0
[0.  0.5 0.5 0. ]
1
B
1
[0.5 0.  0.5 0. ]
0
A
0
[0.  0.5 0.5 0. ]
1
B
1
[0.5 0.  0.5 0. ]
2
C
2
[0.33333333 0.33333333 0.         0.33333333]
1
B
1
[0.5 0.  0.5 0. ]
0
A
0
[0.  0.5 0.5 0. ]
2
C
2
[0.33333333 0.33333333 0.         0.33333333]
1
B
1
[0.5 0.  0.5 0. ]
0
A
0
[0.  0.5 0.5 0. ]
2
C
2
[0.33333333 0.33333333 0.         0.33333333]
3
D
3
[0.5 0.5 0.  0. ]
1
B
1
[0.5 0.  0.5 0. ]
2
C
2
[0.33333333 0.33333333 0.         0.33333333]
0
A
0
[0.  0.5 0.5 0. ]
1
B
1
[0.5 0.  0.5 0. ]
0
A
0
[0.  0.5 0.5 0. ]
2
C
2
[0.33333333 0.33333333 0.         0.33333333]
0
A
0
[0.  0.5 0.5 0. ]
2
C
2
[0.33333333 0.33333333 0

In [2]:
import pandas as pd
import os
dir_path = 'test'
file_list = [os.path.join(dir_path, f) for f in os.listdir(dir_path) if f.endswith('.csv')]
df_list = []
for file in file_list:
    df = pd.read_csv(file)
    df_list.append(df)
merged_df = pd.concat(df_list)

# merged_df.to_csv('merged_file.csv', index=False)